// <auto-generated />
namespace Expenses.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AccountChangeBalancePrecision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountChangeBalancePrecision));
        
        string IMigrationMetadata.Id
        {
            get { return "201507261719471_AccountChangeBalancePrecision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
